---
title: "20.Julho - Acompanhamento do Cenário 5"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readxl)
library(stringr)
library(janitor)
library(ggplot2)
library(tidytext)
library(lubridate)
library(patchwork)
```

```{r,include=FALSE}
#Importa Bases
cenario_5<- read_excel(path = '2-base/cenario_5 - ocs_atualizado_2.junho VERSÃO CORRIGIDA ALINI (1).xlsx') %>% janitor::clean_names()
fitro_cen_5 <- unique(cenario_5 %>% filter(!is.na(coluna1)) %>% select(coluna1))

#Importa status de cada ocs
status_ocs_cenario_5<- read_excel(path = '2-base/Status_ocs_cenario_5.xlsx') %>% janitor::clean_names() %>% 
  group_by(data_inclusao,nome_empresa, nome_filial,ordem_compra,comprador,status) %>% summarise(gasto = sum(as.numeric(gasto))) %>% 
  mutate(aprovador = if_else(gasto<=3000,'comprador',
                         if_else(gasto>3000&gasto<=30000,'comprador e coordenador',
                                 if_else(gasto>30000,'gerente','outro'))),
         data_inclusao=as_date(data_inclusao),
         'dias_em_aberto' = Sys.Date()-data_inclusao
         )

cenario_5_versao_final <- cenario_5 %>% left_join(status_ocs_cenario_5,by = c('coluna1'='ordem_compra'))
```

## Quantidade de OCs por status

```{r warning=FALSE, r,message=FALSE,echo=FALSE}
teste <- janitor::tabyl(status_ocs_cenario_5$status) %>% janitor::adorn_pct_formatting() %>%  data.frame() %>% arrange(desc(n))
ggplot(teste,aes(x =reorder(status_ocs_cenario_5.status,n), y = n))+
  geom_col(fill='forestgreen')+
  coord_flip()+
  ylab('')+xlab('')+
  theme_classic()+
  geom_text(aes(label=paste0(format(n,big.mark = '.',small.mark = ','),' - ',percent)),hjust=-.03,size=4)+
  scale_y_continuous(limits = c(0,max(teste$n)*1.2))+
 labs(caption = paste0("Total de OCs: ",format(sum(teste$n),big.mark = '.')))
```

## Produção de Novas OCs por dia

```{r,echo=FALSE,warning=FALSE,message=FALSE}
graf <- status_ocs_cenario_5 %>% group_by(data_inclusao,ordem_compra) %>% summarise(total=1) %>% ungroup() %>% group_by(data_inclusao) %>% summarise(total=sum(total)) %>% arrange(desc(data_inclusao))

  ggplot(graf, aes(x = data_inclusao,y = total))+
  geom_line()+
  geom_hline(yintercept = mean(graf$total),color='blue')+
  theme_classic()+
  scale_x_date(breaks = 'day',date_labels = "%d/%b")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1),legend.position = 'top',legend.title = element_blank())+
  ylab('')+xlab('')+labs(caption = 'Linha azul: Média por dia')+
  geom_text(aes(label=total),hjust=.1, angle=90,color='blue')

```

## Status das OCs desde sua criação

```{r,echo=FALSE,warning=FALSE,message=FALSE}
status_ocs_cenario_5 %>% group_by(data_inclusao,ordem_compra,status) %>% summarise(total=1) %>% ungroup() %>% group_by(data_inclusao,status) %>% summarise(total=sum(total)) %>% arrange(desc(data_inclusao)) %>% filter(status %in% c('CADASTRADA','CANCELADA','RECUSADA')) %>% 
  ggplot(aes(x = data_inclusao,y = total, color=status))+
  geom_line()+
  theme_classic()+
  scale_x_date(breaks = 'day',date_labels = "%d/%b")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1),legend.position = 'top',legend.title = element_blank())+
  ylab('')+xlab('')+
  geom_text(aes(label=total),vjust=.09, angle=90)

```


## OCs pendentes de liberação por comprador

```{r,echo=FALSE,warning=FALSE,message=FALSE}
status_ocs_cenario_5 %>%
  filter(status %in% c('CADASTRADA','CANCELADA','RECUSADA')) %>%
           group_by(comprador,status,ordem_compra) %>% summarise(total = 1) %>% ungroup() %>% 
  group_by(comprador,status) %>% summarise(total=sum(total)) %>% arrange(desc(total)) %>% 
  ggplot(aes(x = reorder(comprador,total),y = total))+
  geom_col(fill='forestgreen')+
  coord_flip()+
  geom_text(aes(label=total),size=4)+
  facet_grid(~status,scales = 'free')+
  ylab('')+xlab('')+
  theme_classic()

DT::datatable(status_ocs_cenario_5 %>% filter(status %in% c('CADASTRADA','CANCELADA','RECUSADA')),
              extensions = 'Buttons', options = list(
    dom = 'Bfrtip',
    buttons = 
      list('copy', 'print', list(
        extend = 'collection',
        buttons = c('csv', 'excel', 'pdf'),
        text = 'Download')))) %>%
  DT::formatStyle(columns =
                    c('data_inclusao','nome_empresa','nome_filial','ordem_compra','comprador','status','gasto','aprovador','dias_em_aberto'),
                  `font-size` = '12px')
```
